declare const prepareException: (this: any, target: any, error: Error, ...args: any[]) => any;
export default prepareException;
